name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install decision kernel
        run: |
          pip install -e services/decision_kernel
      - name: Install API (dev)
        run: |
          pip install -e services/api[dev]
      - name: Run tests
        run: |
          pytest -q

